name: deploy

on:
    push:
        branches: [deploy]

jobs:

    deploy:

        runs-on: ubuntu-latest

        steps:
        -   name: Check out the repo
            uses: actions/checkout@v4
        -   name: Install SSH key
            uses: webfactory/ssh-agent@v0.9.1
            with:
                ssh-private-key: ${{ secrets.SSH_KEY_SERVER }}
        -   name: Push to server
            run: |
                ssh -o StrictHostKeyChecking=no opsrv@omnipathdb.org 'bash -s' < 'scripts/update-and-run.sh'
