name: deploy

on:
    push:
        branches: [deploy]

jobs:

    deploy:

        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash -e {0}

        with: # Set the secret as an input
            ssh_key: ${{ secrets.SSH_KEY_SERVER }}

        env:
            ssh_key: ${{ secrets.SSH_KEY_SERVER }}

        steps:
        -   name: Push to server

            run: |
                ssh -o StrictHostKeyChecking=no -i $ssh_key opsrv@omnipathdb.org 'update-and-run.sh'
